TweetnHash_New/TweetnHash/TweetnHash/Controllers/TweetHashController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TweetnHash.Controllers
{
    public class TweetHashController : Controller
    {
        // GET: TweetHash
        public ActionResult Dashboard()
        {
            return View();
        }
    }
}

TweetnHash_New/TweetnHash/TweetnHash/Views/TweetHash/Create.cshtml
@model TweetnHash.Models.SocialMediaAccount
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
<form>
    <div class="form-group">
        @Html.LabelFor(m => m.FaceBookAccount.FaceBookId)
        @Html.TextBoxFor(m => m.FaceBookAccount.FaceBookId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m=>m.TwitterAccount.TwitterId)
        @Html.TextBoxFor(m=>m.TwitterAccount.TwitterId,new { @class ="form-control"})
    </div>
    <div class="form-group"></div>
    <div class="form-group"></div>
    <div class="form-group"></div>
    <div class="form-group"></div>
</form>

TweetnHash_New/TweetnHash/TweetnHash/Views/TweetHash/Dashboard.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TweetnHash</title>
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        .navbar {
            background-color: darkslategray;
            color: white;
        }
    </style>



</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TweetnHash", "Dashboard", "TweetHash", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Dashboard", "TweetHash")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @*@RenderBody()*@
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - TweetnHash</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*@RenderSection("scripts", required: false)*@
</body>
</html>